Documentation, Scripting updates: FULLDOC, README, waifu
// FULLDOC: Updated from documentation of flags that require an argument to full guide, add extra sections for scripting docs
// README: Updated from Wall of documentation to a description
// WAIFU:
- Added custom error codes
- Moved DEL_PRINT block higher up
- Fix typos

diff --git a/waifu b/waifu
--- a/waifu
+++ b/waifu
@@ -9,7 +9,6 @@
 
 
 # hushlogin-type implementation to hide script usage
-
 KILLSWITCH="$HOME/.waifulock"
 if [[ -f "$KILLSWITCH" ]]; then
   exit 0
@@ -307,7 +306,7 @@ chafa_valid() {
 # test if gnu getopt
 x="$(getopt -T;echo $?)"
 if ! ((x >=4)); then
-  print_err_msg "Getopt is not GNU!" 1
+  print_err_msg "Getopt is not GNU!" 3
 fi
 
 # get flags
@@ -316,7 +315,7 @@ PARAM=$(getopt -o "ho:n:tv:pi:g:a:s:r:G:" -l "help,output:,nsfw:,termux,view:,pr
 # check if getopt failed for some reason
 PARAM_RC="$?"
 [[ "$PARAM_RC" != "0" ]] && \
-  print_err_msg "Failed to parse parameters!" $PARAM_RC
+  print_err_msg "Failed to parse parameters!" 4
 
 # API
 WAIFU_URL="https://api.waifu.im/images"
@@ -525,7 +524,7 @@ while true; do
               shift 2
               continue
             else
-              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
+              print_err_msg "Failed to parse arguments! Unknown option: $2" 4
             fi
             ;;
         esac
@@ -544,7 +543,7 @@ while true; do
               shift 2
               continue
             else
-              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
+              print_err_msg "Failed to parse arguments! Unknown option: $2" 4
             fi
             ;;
         esac
@@ -563,7 +562,7 @@ while true; do
               shift 2
               continue
             else
-              print_err_msg "Failed to parse arfuments! Unknown option: $2"
+              print_err_msg "Failed to parse arguments! Unknown option: $2" 4
             fi
             ;;
         esac
@@ -615,7 +614,7 @@ while true; do
               shift 2
               continue
             else
-              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
+              print_err_msg "Failed to parse arguments! Unknown option: $2" 4
             fi
             ;;
         esac
@@ -634,7 +633,7 @@ while true; do
               shift 2
               continue
             else
-              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
+              print_err_msg "Failed to parse arguments! Unknown option: $2" 4
             fi
             ;;
           esac
@@ -653,7 +652,7 @@ while true; do
               shift 2
               continue
             else
-              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
+              print_err_msg "Failed to parse arguments! Unknown option: $2" 4
             fi
             ;;
           esac
@@ -672,7 +671,7 @@ while true; do
               shift 2
               continue
             else
-              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
+              print_err_msg "Failed to parse arguments! Unknown option: $2" 4
             fi
             ;;
           esac
@@ -691,7 +690,7 @@ while true; do
               shift 2
               continue
             else
-              print_err_msg "Failed to parse arguments! Unknown option: $2" 1
+              print_err_msg "Failed to parse arguments! Unknown option: $2" 4
             fi
             ;;
         esac
@@ -728,7 +727,7 @@ while true; do
       break
       ;;
     *)
-      print_err_msg "Failed to parse arguments! Unknown option: $1" 1
+      print_err_msg "Failed to parse arguments! Unknown option: $1" 4
       ;;
   esac
 done
@@ -738,6 +737,14 @@ done
 #   VALIDATION
 # # # # # # #
 # ------------------------------------------------------------------
+
+# check if no-print was passed
+if [[ "$DEL_PRINT" == "1" ]]; then
+  PRINT=0
+  RAW_URL=0
+  SHOW_JSON=0
+  PRINT_INT_VAR=0
+fi
 
 {
   {
@@ -756,13 +763,15 @@ done
     done
 
     if [[ "$CMD_FAILED" == "1" ]]; then
-      echo "$SCRIPT: Missing commands!" >&2
-      printf "\n{\n"
+      if [[ "$DEL_PRINT" == "1" ]]; then
+        :
+      else
+        echo "$SCRIPT: Missing commands!" >&2
+      fi
       for MISSING in "${MISSING_CMD[@]}"; do
         printf "$MISSING\n"
       done
-      printf "}\n"
-      exit 1
+      exit 2 # missing commands
     fi
   }
 }
@@ -841,15 +850,7 @@ fi
 
 
 [[ -z "$IMAGE_URL" || "$IMAGE_URL" == "null" || ! "$IMAGE_URL" =~ ^https:\/\/cdn\.waifu\.im\/ ]] && \
-  print_err_msg "Failed to fetch valid image data!" 1
-
-# check if no-print was passed
-if [[ "$DEL_PRINT" == "1" ]]; then
-  PRINT=0
-  RAW_URL=0
-  SHOW_JSON=0
-  PRINT_INT_VAR=0
-fi
+  print_err_msg "Failed to fetch valid image data!" 5
 
 # save to file
 if [[ "$OUTPUT" == "1" ]]; then
@@ -861,7 +862,7 @@ if [[ "$OUTPUT" == "1" ]]; then
       wget "$IMAGE_URL" -O "${OUTPUT_NAME}.${E_EXT}"
     fi
   else
-    print_err_msg "Missing command for flag -o: wget" 1
+    print_err_msg "Missing command for flag -o: wget" 2
   fi
 fi
 
@@ -870,7 +871,7 @@ if [[ "$TERMUX" == "1" ]]; then
   if command -v termux-open &>/dev/null; then
     termux-open "$IMAGE_URL"
   else
-    print_err_msg "termux-open not available!" 1
+    print_err_msg "termux-open not available!" 2
   fi
 fi
 
@@ -896,14 +897,14 @@ if [[ "$VIEW" == "1" ]]; then
   case "$VIEW_OPT" in
     c|chafa)
       command -v chafa &>/dev/null || {
-      print_err_msg "Missing command for flag -vc: chafa" 1
+      print_err_msg "Missing command for flag -vc: chafa" 2
       }
       curl -s "$IMAGE_URL" | chafa
       ;;
 
     s|sixel)
       command -v img2sixel &>/dev/null || {
-      print_err_msg "Missing library for flag -vs: libsixel" 1
+      print_err_msg "Missing command for flag -vs: img2sixel" 2
       }
 
       curl -s "$IMAGE_URL" | img2sixel
@@ -925,7 +926,7 @@ fi
 
 if [[ "$PRINT_INT_VAR" == "1" ]]; then
   if [[ -z "$NAME_VAR" ]]; then
-    print_err_msg "Variable not found!"
+    print_err_msg "Variable not found!" 6
   else
     if declare -p "$INT_VAR" 2>/dev/null | grep -q '^declare -a'; then
       for VAR in "${NAME_VAR[@]}"; do
